spring.data.rest:
  returnBodyOnCreate: true
  returnBodyOnUpdate: true

logging.level: INFO
logging.level.org.hibernate.type.descriptor.sql: trace

spring:
  jpa:
    show-sql: true
    hibernate.ddl-auto: create-drop
server.port: 8080

spring.jackson.serialization.fail_on_empty_beans: false
